export const months = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export const activities = [
  {
    src: 'assets/images/virtual-challenge/activity-icon/canoe_kayak_webp.webp',
    alt: 'Canoe Kayak',
    name: 'Canoe Kayak',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/climb_webp.webp',
    alt: 'Climb',
    name: 'Climb',
  },
  // {
  //   src: 'assets/images/virtual-challenge/activity-icon/wrestling_dragons.svg',
  //   alt: 'wrestling dragons',
  //   name: 'wrestling dragons',
  // },
  {
    src: 'assets/images/virtual-challenge/activity-icon/cycle_webp.webp',
    alt: 'Cycle',
    name: 'Cycle',
  },
  // {
  //   src: 'assets/images/virtual-challenge/activity-icon/running_from_bears.svg',
  //   alt: 'running from bears',
  //   name: 'running from bears',
  // },
  {
    src: 'assets/images/virtual-challenge/activity-icon/dog_walk_webp.webp',
    alt: 'Dog Walk',
    name: 'Dog Walk',
  },
  // {
  //   src: 'assets/images/virtual-challenge/activity-icon/typical_viking_stuff.svg',
  //   alt: 'typical viking stuff',
  //   name: 'typical viking stuff',
  // },
  {
    src: 'assets/images/virtual-challenge/activity-icon/download_paceline_app_webp.webp',
    alt: 'Download Paceline App',
    name: 'Download Paceline App',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/golf_webp.webp',
    alt: 'Golf',
    name: 'Golf',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/group_fitness_class_webp.webp',
    alt: 'Group Fitness Class',
    name: 'Group Fitness Class',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/hike_webp.webp',
    alt: 'Hike',
    name: 'Hike',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/hitt_workout_webp.webp',
    alt: 'Hitt Workout',
    name: 'Hitt Workout',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/ice_skate_webp.webp',
    alt: 'Ice Skate',
    name: 'Ice Skate',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/meditate_webp.webp',
    alt: 'Meditate',
    name: 'Meditate',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/mountain_bike_gravel_bike_webp.webp',
    alt: 'Mountain Bike Gravel Bike',
    name: 'Mountain Bike Gravel Bike',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/other_gym_things_webp.webp',
    alt: 'Other Gym Things',
    name: 'Other Gym Things',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/pilates_webp.webp',
    alt: 'Pilates',
    name: 'Pilates',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/push_ups_webp.webp',
    alt: 'Push Ups',
    name: 'Push Ups',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/register_for_a_2023_ragnar_webp.webp',
    alt: 'Register For a 2023 Ragnar',
    name: 'Register For a 2023 Ragnar',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/row_webp.webp',
    alt: 'Row',
    name: 'Row',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/run_Webp.webp',
    alt: 'Run',
    name: 'Run',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/ski_webp.webp',
    alt: 'Ski',
    name: 'Ski',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/snowboard_Webp.webp',
    alt: 'Snowboard',
    name: 'Snowboard',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/snowshoe_webp.webp',
    alt: 'Snowshoe',
    name: 'Snowshoe',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/sports_with_balls_webp.webp',
    alt: 'Sports With Balls',
    name: 'Sports With Balls',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/strech_webp.webp',
    alt: 'Strech',
    name: 'Strech',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/strength_train_webp.webp',
    alt: 'Strength Train',
    name: 'Strength Train',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/sup_standup_paddle_board_webp.webp',
    alt: 'Sup Standup Paddle Board',
    name: 'Sup Standup Paddle Board',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/surf_webp.webp',
    alt: 'Surf',
    name: 'Surf',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/swim_webp.webp',
    alt: 'Swim',
    name: 'Swim',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/trail_run_webp.webp',
    alt: 'Trail Run',
    name: 'Trail Run',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/walk_webp.webp',
    alt: 'Walk',
    name: 'Walk',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/yoga_webp.webp',
    alt: 'Yoga',
    name: 'Yoga',
  },
  {
    src: 'assets/images/virtual-challenge/activity-icon/other_webp.webp',
    alt: 'Other',
    name: 'Other',
  },
];

export const successActivityMessages = [
  'Exercise prevents signs of aging and you are looking FRESH!',
  'Fun fact! You use 200 muscles to take a single step forward',
  'Geeze! Who are you trying to impress? Nice work today.',
  'The only exercise your neighbor did was run out of toilet paper.',
  'Who needs a sweater...after that workout you are the sweater! #sweataweatha',
  'Oh my quad, Becky! Look at her squat!',
  'Unrolling the yoga mat takes a lot of energy.',
  'Look good. Feel Good. Have you geared up in the Ragnar Gear store with our official 31 Day Challenge apparel?!',
  'You can wear yoga pants and not do yoga.',
  `Did you even workout if you don't share it online? Tag us on social @runragnar`,
  `Don't you feel accomplished? Great job today.`,
  'I run my mouth faster than I can run a mile.',
  `You're going to be proud of yourself tomorrow for moving today.`,
  `To show good sportsmanship, please refrain from making little racecar noises as you pass your fellow opponents.`,
  `Life has its ups and downs, some call them squats.`,
  `You know who can't medidate. DONUTS. They can't find their center. Remember...you are not a donut.`,
  `Cardio is hardio.`,
  `“Stars can’t shine without darkness.” – That’s us telling you that you are a star. .`,
  `Did you know you're more sore the day after you workout? I wonder how you'll feel on February 1?`,
  `Look at you go! Round of applause.`,
  `Is that a strut or are you just sore?`,
  `It’s never too late, and you are never too old to become better.`,
  `More activities. More chances to win the 31 Day Challenge Grand Prize and FEEL GOOD about yourself!`,
  `Will run for...honestly anything.`,
  `You hear about that race between lettuce and the tomato? The lettuce was a “head” and the tomato needed to “ketchup”`,
  `What do you call a free treadmill? Outside`,
  `Why do dogs run in circles? Have you ever tried to run in squares?`,
  `Before you criticize someone, you should walk a mile in their shoes. Then you have their shoes. And you're a mile away.`,
  `If you trip while running, it just means you're well traveled. Get it. Because it's a trip.`,
  `It's not bragging when I tell you how many miles I ran today. It's flaunting.`,
  `The truth is you can always run faster, but sometimes the truth hurts.`,
  `Each foot is made up of 26 bones, 30 joints and more than 100 muscles, tendons and ligaments. What will you do with this information we leave up to you.`,
  `Your heart is the hardest working muscle in your body. It beats approximately 100,000 times per day, pumping almost 2,000 gallons of blood.`,
  `Trail Running or Road Running. That's the tough question. Good thing Ragnar has both of those.`,
  `What's the point of your pinky toe? The tip of it.`,
  `The more activities you log, the higher chance you have at winning our grand prize! Could it be you?`,
  `Wow...you're good at this. It must...run...in your genes.`,
  `Why did the snowman pull a muscle? He forget to warm up.`,
  `No matter the speed of that last mile, you are lapping everyone on the couch.`,
];
